### PR TITLE
add minecraft 0.30 and 0.0.a23_01

### PR DESCRIPTION
**Pull request by btplayzxgit**
here you go radman

### CODE REVIEW

**Comment by Alexghduu** [comment]
add to minecraft 3.0

**Comment by radmanplays** [comment]
no

**Comment by btplayzxgit** [comment]
@radmanplays why is the title of online mc "radmanplays.github.io" you don't have to do that anymore, just name it "online-mc" and setup github pages

**Comment by radmanplays** [comment]
bc then the url would be radmanplays.github.io/online-mc and it would be too long

**Comment by radmanplays** [comment]
also peytonplayz said hes adding byte code obfuscation to hes minecraft ports like 0.30 so you cant just change eaglercraft to klockcraft bc the text that says eaglercraft or (made by peytonplayz) would look like this : 79 6f 75 20 61 72 65 20 61 20 64 75 6d 62 61 73 73

**Comment by radmanplays** [comment]
AND if your change it a big text thats says "YOU ARE AND SKID" would appear

**Comment by btplayzxgit** [comment]
@radmanplays ppl were waiting so i had to copy 0.30

**Comment by btplayzxgit** [comment]
Capture

@radmanplays can you send that to my discord server pls

**Comment by radmanplays** [comment]
sure but bc of an admin this is what the klockcraft discord looks like now : 
image

**Comment by btplayzxgit** [comment]
hey tell them to change it back @radmanplays

**Comment by btplayzxgit** [comment]
my discord :(

**Comment by btplayzxgit** [comment]
@radmanplays mind if i use the default online mc background? i will credit you :)

**Comment by radmanplays** [comment]
sure, where do you want to use it?

**Comment by btplayzxgit** [comment]
i just want to use it for the login page on klockcraft 1.9.3 if thats okay with you, i'll put ur name in the README

**Comment by radmanplays** [comment]
> i just want to use it for the login page on klockcraft 1.9.3 if thats okay with you, i'll put ur name in the README

ok

**Comment by btplayzxgit** [comment]
okay thanks

**Pull request closed without merging**
