### PR TITLE
thingy did a thing so that it better fr

### PR DESCRIPTION
**Pull request by Edward-ba**
now u can download it then double click on the HTML files in file explorer or files on linux to view cuz better ong

### CODE REVIEW

**Comment by Edward-ba** [comment]
is better

**Comment by radmanplays** [comment]
> is better
> 

you can just use simple web server to open it up on your pc

**Comment by Edward-ba** [comment]
but like still better and it works with web browser and files

**Comment by Edward-ba** [comment]
i forgot a bit of code cuz i small brain

**Comment by Edward-ba** [comment]
im top tier coder ong fr fr

**Comment by radmanplays** [comment]
> im top tier coder ong fr fr
> 

use this : https://simplewebserver.org/

**Pull request closed without merging**
